APP_TITLE = "CrossPatch - A Crossworlds Mod Manager"
APP_VERSION = "1.1.5"
CONFIG_FILE = "mod_manager_config.json"
UPDATE_URL = "https://api.github.com/repos/NickPlayzGITHUB/CrossPatch/releases/latest"
GB_API_URL = "https://gamebanana.com/apiv11/Mod/"
BROWSER_USER_AGENT = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
GITHUB_REDIRECT = "https://github.com/NickPlayzGITHUB/CrossPatch/releases/"
STEAM_APP_ID = "2486820"